[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat" 
  status = 200

[[redirects]]
  from = "/search/"
  to = "https://google.com"
  status = 200

[[plugins]]
package = "netlify-plugin-inline-functions-env"